export const translationEn = {
  locale: 'en',
  Header: {
    subTitle: 'Real Time',
    lastUpdate: 'Last Update',
    utcTime: 'UTC Time'
  },
  Configurations: {
    information:
      'Time lapse between site updates. Turn the switch on and pick a time to refresh the statistics or turn off the switch to freeze updates',
    timeSelect: 'minute',
    timeSelectPl: 'minutes',
    timeSelectHour: 'hour'
  },
  Corona: {
    statisticsTab: 'Statistcs',
    newsTab: 'News',
    aboutTab: 'About'
  },
  Global: {
    cardTitle: 'Global Statistics',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered'
  },
  Today: {
    cardTitle: 'Worldwide',
    information: 'Occurrences in the past 24 hours.',
    informationCountry: "Today's country with more deaths.",
    deaths: 'Deaths',
    confirmed: 'Confirmed'
  },
  TableStats: {
    cardTitle: 'Countries Statistics',
    inputSearchCountry: 'Search Country',
    countries: 'Countries',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered',
    critical: 'Critical',
    total: 'Total',
    last24h: 'Last 24h',
    percent: 'Percent',
    paginationPrevious: 'Previous',
    paginationNext: 'Next',
    paginationOf: 'of',
    paginationRows: 'rows',
    paginationPage: 'Page'
  },
  About: {
    cardTitle: 'About',
    line1: 'Thank you for choosing {{site}} We appreciate it!',
    line2: 'This site was developed to bring information regarding the corona virus (covid-19) in REAL TIME!',
    line3:
      'In addition to that, the News tab contains important information and links to let you know everything about COVID-19 that is happening around the globe.',
    line4: 'Use the protection tips to find out a better way to protect yourself and your loved ones!',
    line5:
      'This website is the result of my work and my wish to share true/correct information regarding the covid-19 to support our worldwide fight against it.',
    line6: "If you've found this website useful, please, consider making a donation to support my work!",
    dataSource: 'Data Sources'
  }
};

export const translationPtBr = {
  locale: 'pt',
  Header: {
    subTitle: 'Tempo Real',
    lastUpdate: 'Última atualização',
    utcTime: 'Horário UTC'
  },
  Configurations: {
    information:
      'Intervalo de tempo entre as atualizações do site. Acione o interruptor e escolha um horário para atualizar as estatísticas ou desligue o interruptor para congelar as atualizações',
    timeSelect: 'minuto',
    timeSelectPl: 'minutos',
    timeSelectHour: 'hora'
  },
  Corona: {
    statisticsTab: 'Estatísticas',
    newsTab: 'Notícias',
    aboutTab: 'Sobre nós'
  },
  Global: {
    cardTitle: 'Estatísticas Globais',
    confirmed: 'Confirmado',
    infecteds: 'Infectados',
    deaths: 'Mortes',
    recovered: 'Recuperados'
  },
  Today: {
    cardTitle: 'No mundo todo',
    information: 'Ocorrências nas últimas 24 horas.',
    informationCountry: 'País com mais mortes hoje.',
    deaths: 'Mortes',
    confirmed: 'Confirmado'
  },
  TableStats: {
    cardTitle: 'Estatísticas por País',
    inputSearchCountry: 'Procurar País',
    countries: 'Países',
    confirmed: 'Confirmado',
    infecteds: 'Infectados',
    deaths: 'Mortes',
    recovered: 'Recuperados',
    critical: 'Crítico',
    total: 'Total',
    last24h: 'Últimas 24h',
    percent: 'Porcentagem',
    paginationPrevious: 'Anterior',
    paginationNext: 'Próxima',
    paginationOf: 'de',
    paginationRows: 'linhas',
    paginationPage: 'Página'
  },
  About: {
    cardTitle: 'Sobre',
    line1: 'Obrigado por escolher o {{site}} Nós agradecemos!',
    line2: 'Esse site foi desenvolvido para trazer informações sobre o coronavírus (covid-19) em TEMPO REAL!',
    line3:
      'Além disso, a guia Notícias contém informações e links importantes para que você saiba tudo sobre o COVID-19 ao redor de todo o mundo.',
    line4: 'Use as dicas de proteção para descobrir uma maneira melhor de proteger você e seus entes queridos!',
    line5:
      'Esse site é o resultado do meu trabalho e meu desejo de compartilhar informações verdadeiras/corretas sobre o covid-19 para apoiar nossa luta mundial contra ele.',
    line6: 'Se você achou esse site útil, considere fazer uma doação para apoiar meu trabalho!',
    dataSource: 'Fontes de dados'
  }
};

export const translationEs = {
  locale: 'es',
  Header: {
    subTitle: 'Real Time',
    lastUpdate: 'Last Update',
    utcTime: 'UTC Time'
  },
  Configurations: {
    information: 'Time lapse between site updates. Turn the switch on and pick a time to refresh the statistics',
    timeSelect: 'minute',
    timeSelectPl: 'minutes',
    timeSelectHour: 'hour'
  },
  Corona: {
    statisticsTab: 'Statistcs',
    newsTab: 'News',
    aboutTab: 'About'
  },
  Global: {
    cardTitle: 'Global Statistics',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered'
  },
  Today: {
    cardTitle: 'Worldwide',
    information: 'Occurrences in the past 24 hours.',
    informationCountry: "Today's country with more deaths.",
    deaths: 'Deaths',
    confirmed: 'Confirmed'
  },
  TableStats: {
    cardTitle: 'Countries Statistics',
    inputSearchCountry: 'Search Country',
    countries: 'Countries',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered',
    critical: 'Critical',
    total: 'Total',
    last24h: 'Last 24h',
    percent: 'Percent',
    paginationPrevious: 'Previous',
    paginationNext: 'Next',
    paginationOf: 'of',
    paginationRows: 'rows',
    paginationPage: 'Page'
  },
  About: {
    cardTitle: 'About',
    firstP: 'Thank you for using my website covid19realtime.info!',
    secondP:
      'The goal of covid19realtime.info is to provide the latest information on the COVID-19 coronavirus and to make that information more accessible',
    thirdP:
      "This site is designed, developed and funded by myself (leobpaschoal). It is the result of constant work; updating, fixing and maintaining in order to provide the service. If you've found the site helpful or useful then please consider donate to support my work.",
    dataSource: 'Data Sources'
  }
};

export const countriesTranslated = [
  { originalName: 'USA', brName: 'EUA', esName: 'Estados Unidos' },
  { originalName: 'Italy', brName: 'Itália', esName: 'Italia' },
  { originalName: 'China', brName: 'China', esName: 'China' },
  { originalName: 'Spain', brName: 'Espanha', esName: 'España' },
  { originalName: 'Germany', brName: 'Alemanha', esName: 'Alemania' },
  { originalName: 'France', brName: 'França', esName: 'Francia' },
  { originalName: 'Iran', brName: 'Irã', esName: 'Iran' },
  { originalName: 'UK', brName: 'Reino Unido', esName: 'Reino Unido' },
  { originalName: 'Switzerland', brName: 'Suíça', esName: 'Suiza' },
  { originalName: 'Netherlands', brName: 'Países Baixos', esName: 'Países Bajos' },
  { originalName: 'Belgium', brName: 'Bélgica', esName: 'Bélgica' },
  { originalName: 'S. Korea', brName: 'Coreia do Sul', esName: 'Corea del Sur' },
  { originalName: 'Turkey', brName: 'Peru', esName: 'Turquía' },
  { originalName: 'Austria', brName: 'Áustria', esName: 'Austria' },
  { originalName: 'Canada', brName: 'Canadá', esName: 'Canadá' },
  { originalName: 'Portugal', brName: 'Portugal', esName: 'Portugal' },
  { originalName: 'Norway', brName: 'Noruega', esName: 'Noruega' },
  { originalName: 'Israel', brName: 'Israel', esName: 'Israel' },
  { originalName: 'Brazil', brName: 'Brasil', esName: 'Brasil' },
  { originalName: 'Australia', brName: 'Austrália', esName: 'Australia' },
  { originalName: 'Sweden', brName: 'Suécia', esName: 'Suecia' },
  { originalName: 'Czechia', brName: 'Czechia', esName: 'Chequia' },
  { originalName: 'Ireland', brName: 'Irlanda', esName: 'Irlanda' },
  { originalName: 'Malaysia', brName: 'Malásia', esName: 'Malasia' },
  { originalName: 'Denmark', brName: 'Dinamarca', esName: 'Dinamarca' },
  { originalName: 'Chile', brName: 'Chile', esName: 'Chile' },
  { originalName: 'Luxembourg', brName: 'Luxemburgo', esName: 'Luxemburgo' },
  { originalName: 'Ecuador', brName: 'Equador', esName: 'Ecuador' },
  { originalName: 'Japan', brName: 'Japão', esName: 'Japón' },
  { originalName: 'Poland', brName: 'Polônia', esName: 'Polonia' },
  { originalName: 'Romania', brName: 'Romênia', esName: 'Rumania' },
  { originalName: 'Pakistan', brName: 'Paquistão', esName: 'Pakistán' },
  { originalName: 'Russia', brName: 'Rússia', esName: 'Rusia' },
  { originalName: 'Philippines', brName: 'Filipinas', esName: 'Filipinas' },
  { originalName: 'Thailand', brName: 'Tailândia', esName: 'Tailandia' },
  { originalName: 'Saudi Arabia', brName: 'Arábia Saudita', esName: 'Arabia Saudita' },
  { originalName: 'Indonesia', brName: 'Indonésia', esName: 'Indonesia' },
  { originalName: 'South Africa', brName: 'África do Sul', esName: 'Sudáfrica' },
  { originalName: 'Finland', brName: 'Finlândia', esName: 'Finlandia' },
  { originalName: 'Greece', brName: 'Grécia', esName: 'Grecia' },
  { originalName: 'India', brName: 'Índia', esName: 'India' },
  { originalName: 'Iceland', brName: 'Islândia', esName: 'Islandia' },
  { originalName: 'Panama', brName: 'Panamá', esName: 'Panamá' },
  { originalName: 'Dominican Republic', brName: 'República Dominicana', esName: 'República Dominicana' },
  { originalName: 'Peru', brName: 'Peru', esName: 'Perú' },
  { originalName: 'Mexico', brName: 'México', esName: 'Mexico' },
  { originalName: 'Singapore', brName: 'Cingapura', esName: 'Singapur' },
  { originalName: 'Argentina', brName: 'Argentina', esName: 'Argentina' },
  { originalName: 'Serbia', brName: 'Sérvia', esName: 'Serbia' },
  { originalName: 'Slovenia', brName: 'Eslovênia', esName: 'Eslovenia' },
  { originalName: 'Croatia', brName: 'Croácia', esName: 'Croacia' },
  { originalName: 'Diamond Princess', brName: 'Diamond Princess', esName: 'Diamond Princess' },
  { originalName: 'Colombia', brName: 'Colômbia', esName: 'Colombia' },
  { originalName: 'Estonia', brName: 'Estônia', esName: 'Estonia' },
  { originalName: 'Hong Kong', brName: 'Hong Kong', esName: 'Hong Kong' },
  { originalName: 'Qatar', brName: 'Catar', esName: 'Katar' },
  { originalName: 'Egypt', brName: 'Egito', esName: 'Egipto' },
  { originalName: 'UAE', brName: 'Emirados Árabes Unidos', esName: 'Emiratos Árabes Unidos' },
  { originalName: 'Iraq', brName: 'Iraque', esName: 'Irak' },
  { originalName: 'New Zealand', brName: 'Nova Zelândia', esName: 'Nueva Zelanda' },
  { originalName: 'Algeria', brName: 'Argélia', esName: 'Argelia' },
  { originalName: 'Bahrain', brName: 'Barém', esName: 'Bahrein' },
  { originalName: 'Morocco', brName: 'Marrocos', esName: 'Marruecos' },
  { originalName: 'Lithuania', brName: 'Lituânia', esName: 'Lituania' },
  { originalName: 'Lebanon', brName: 'Líbano', esName: 'Líbano' },
  { originalName: 'Armenia', brName: 'Armênia', esName: 'Armenia' },
  { originalName: 'Ukraine', brName: 'Ucrânia', esName: 'Ucrania' },
  { originalName: 'Hungary', brName: 'Hungria', esName: 'Hungría' },
  { originalName: 'Latvia', brName: 'Letônia', esName: 'Letonia' },
  { originalName: 'Bulgaria', brName: 'Bulgária', esName: 'Bulgaria' },
  { originalName: 'Andorra', brName: 'Andorra', esName: 'Andorra' },
  { originalName: 'Bosnia and Herzegovina', brName: 'Bósnia e Herzegovina', esName: 'Bosnia y Herzegovina' },
  { originalName: 'Costa Rica', brName: 'Costa Rica', esName: 'Costa Rica' },
  { originalName: 'Slovakia', brName: 'Eslováquia', esName: 'Eslovaquia' },
  { originalName: 'Tunisia', brName: 'Tunísia', esName: 'Túnez' },
  { originalName: 'Uruguay', brName: 'Uruguai', esName: 'Uruguay' },
  { originalName: 'Taiwan', brName: 'Taiwan', esName: 'Taiwán' },
  { originalName: 'Kazakhstan', brName: 'Cazaquistão', esName: 'Kazajstán' },
  { originalName: 'Moldova', brName: 'Moldova', esName: 'Moldavia' },
  { originalName: 'North Macedonia', brName: 'Macedônia do Norte', esName: 'Macedonia del norte' },
  { originalName: 'Jordan', brName: 'Jordânia', esName: 'Jordán' },
  { originalName: 'Kuwait', brName: 'Kuwait', esName: 'Kuwait' },
  { originalName: 'San Marino', brName: 'San Marino', esName: 'San Marino' },
  { originalName: 'Burkina Faso', brName: 'Burkina Faso', esName: 'Burkina Faso' },
  { originalName: 'Cyprus', brName: 'Chipre', esName: 'Chipre' },
  { originalName: 'Albania', brName: 'Albânia', esName: 'Albania' },
  { originalName: 'Azerbaijan', brName: 'Azerbaijão', esName: 'Azerbaiyán' },
  { originalName: 'Vietnam', brName: 'Vietnã', esName: 'Vietnam' },
  { originalName: 'Réunion', brName: 'Reunião', esName: 'Reunión' },
  { originalName: 'Oman', brName: 'Omã', esName: 'Omán' },
  { originalName: 'Faeroe Islands', brName: 'Ilhas Faroé', esName: 'Islas Feroe' },
  { originalName: 'Ghana', brName: 'Gana', esName: 'Ghana' },
  { originalName: 'Malta', brName: 'Malta', esName: 'Malta' },
  { originalName: 'Uzbekistan', brName: 'Usbequistão', esName: 'Uzbekistán' },
  { originalName: 'Senegal', brName: 'Senegal', esName: 'Senegal' },
  { originalName: 'Ivory Coast', brName: 'Costa do Marfim', esName: 'Costa de Marfil' },
  { originalName: 'Cuba', brName: 'Cuba', esName: 'Cuba' },
  { originalName: 'Brunei', brName: 'Brunei', esName: 'Brunei' },
  { originalName: 'Afghanistan', brName: 'Afeganistão', esName: 'Afganistán' },
  { originalName: 'Venezuela', brName: 'Venezuela', esName: 'Venezuela' },
  { originalName: 'Sri Lanka', brName: 'Sri Lanka', esName: 'Sri Lanka' },
  { originalName: 'Honduras', brName: 'Honduras', esName: 'Honduras' },
  { originalName: 'Palestine', brName: 'Palestina', esName: 'Palestina' },
  { originalName: 'Mauritius', brName: 'Maurícia', esName: 'Mauricio' },
  { originalName: 'Cambodia', brName: 'Camboja', esName: 'Camboya' },
  { originalName: 'Guadeloupe', brName: 'Guadalupe', esName: 'Guadalupe' },
  { originalName: 'Channel Islands', brName: 'Ilhas do Canal', esName: 'Islas del Canal' },
  { originalName: 'Nigeria', brName: 'Nigéria', esName: 'Nigeria' },
  { originalName: 'Belarus', brName: 'Bielorrússia', esName: 'Bielorrusia' },
  { originalName: 'Martinique', brName: 'Martinica', esName: 'Martinica' },
  { originalName: 'Cameroon', brName: 'Camarões', esName: 'Camerún' },
  { originalName: 'Georgia', brName: 'Geórgia', esName: 'Georgia' },
  { originalName: 'Montenegro', brName: 'Montenegro', esName: 'Montenegro' },
  { originalName: 'Kyrgyzstan', brName: 'Quirguistão', esName: 'Kirguistán' },
  { originalName: 'Bolivia', brName: 'Bolívia', esName: 'Bolivia' },
  { originalName: 'Trinidad and Tobago', brName: 'Trindade e Tobago', esName: 'Trinidad y Tobago' },
  { originalName: 'DRC', brName: 'República Democrática do Congo', esName: 'República Democrática del Congo' },
  { originalName: 'Gibraltar', brName: 'Gibraltar', esName: 'Gibraltar' },
  { originalName: 'Mayotte', brName: 'Mayotte', esName: 'Mayotte' },
  { originalName: 'Rwanda', brName: 'Ruanda', esName: 'Ruanda' },
  { originalName: 'Paraguay', brName: 'Paraguai', esName: 'Paraguay' },
  { originalName: 'Liechtenstein', brName: 'Liechtenstein', esName: 'Liechtenstein' },
  { originalName: 'Aruba', brName: 'Aruba', esName: 'Aruba' },
  { originalName: 'Bangladesh', brName: 'Bangladesh', esName: 'Bangladesh' },
  { originalName: 'Monaco', brName: 'Mônaco', esName: 'Mónaco' },
  { originalName: 'Kenya', brName: 'Quênia', esName: 'Kenia' },
  { originalName: 'Isle of Man', brName: 'Ilha de Man', esName: 'Isla del hombre' },
  { originalName: 'Madagascar', brName: 'Madagáscar', esName: 'Madagascar' },
  { originalName: 'Macao', brName: 'Macau', esName: 'Macao' },
  { originalName: 'Guatemala', brName: 'Guatemala', esName: 'Guatemala' },
  { originalName: 'Uganda', brName: 'Uganda', esName: 'Uganda' },
  { originalName: 'Jamaica', brName: 'Jamaica', esName: 'Jamaica' },
  { originalName: 'French Polynesia', brName: 'Polinésia Francesa', esName: 'Polinesia francés' },
  { originalName: 'Zambia', brName: 'Zâmbia', esName: 'Zambia' },
  { originalName: 'French Guiana', brName: 'Guiana Francesa', esName: 'Guayana Francesa' },
  { originalName: 'Barbados', brName: 'Barbados', esName: 'Barbados' },
  { originalName: 'Togo', brName: 'Togo', esName: 'Togo' },
  { originalName: 'El Salvador', brName: 'El Salvador', esName: 'El Salvador' },
  { originalName: 'Bermuda', brName: 'Bermudas', esName: 'Islas Bermudas' },
  { originalName: 'Ethiopia', brName: 'Etiópia', esName: 'Etiopía' },
  { originalName: 'Congo', brName: 'Congo', esName: 'Congo' },
  { originalName: 'Mali', brName: 'Mali', esName: 'Mali' },
  { originalName: 'Niger', brName: 'Níger', esName: 'Níger' },
  { originalName: 'Djibouti', brName: 'Djibuti', esName: 'Djibouti' },
  { originalName: 'Maldives', brName: 'Maldivas', esName: 'Maldivas' },
  { originalName: 'Guinea', brName: 'Guiné', esName: 'Guinea' },
  { originalName: 'Haiti', brName: 'Haiti', esName: 'Haití' },
  { originalName: 'New Caledonia', brName: 'Nova Caledônia', esName: 'Nueva Caledonia' },
  { originalName: 'Tanzania', brName: 'Tanzânia', esName: 'Tanzania' },
  { originalName: 'Equatorial Guinea', brName: 'Guiné Equatorial', esName: 'Guinea Ecuatorial' },
  { originalName: 'Mongolia', brName: 'Mongólia', esName: 'Mongolia' },
  { originalName: 'Bahamas', brName: 'Bahamas', esName: 'Bahamas' },
  { originalName: 'Dominica', brName: 'Dominica', esName: 'Dominica' },
  { originalName: 'Namibia', brName: 'Namíbia', esName: 'Namibia' },
  { originalName: 'Saint Martin', brName: 'São Martinho', esName: 'San Martín' },
  { originalName: 'Greenland', brName: 'Gronelândia', esName: 'Groenlandia' },
  { originalName: 'Myanmar', brName: 'Myanmar', esName: 'Myanmar' },
  { originalName: 'Syria', brName: 'Síria', esName: 'Siria' },
  { originalName: 'Grenada', brName: 'Granada', esName: 'Granada' },
  { originalName: 'Eswatini', brName: 'Eswatini', esName: 'Eswatini' },
  { originalName: 'Cayman Islands', brName: 'Ilhas Cayman', esName: 'Islas Caimán' },
  { originalName: 'Curaçao', brName: 'Curaçao', esName: 'Curazao' },
  { originalName: 'Guyana', brName: 'Guiana', esName: 'Guayana' },
  { originalName: 'Laos', brName: 'Laos', esName: 'Laos' },
  { originalName: 'Libya', brName: 'Líbia', esName: 'Libia' },
  { originalName: 'Mozambique', brName: 'Moçambique', esName: 'Mozambique' },
  { originalName: 'Seychelles', brName: 'Seychelles', esName: 'Seychelles' },
  { originalName: 'Suriname', brName: 'Suriname', esName: 'Surinam' },
  { originalName: 'Angola', brName: 'Angola', esName: 'Angola' },
  { originalName: 'Gabon', brName: 'Gabão', esName: 'Gabón' },
  { originalName: 'Zimbabwe', brName: 'Zimbábue', esName: 'Zimbabue' },
  { originalName: 'Antigua and Barbuda', brName: 'Antígua e Barbuda', esName: 'Antigua y Barbuda' },
  { originalName: 'Cabo Verde', brName: 'Cabo Verde', esName: 'Cabo Verde' },
  { originalName: 'Sudan', brName: 'Sudão', esName: 'Sudán' },
  { originalName: 'Benin', brName: 'Benin', esName: 'Benin' },
  { originalName: 'Eritrea', brName: 'Eritreia', esName: 'Eritrea' },
  { originalName: 'Vatican City', brName: 'Cidade do Vaticano', esName: 'Ciudad del Vaticano' },
  { originalName: 'Sint Maarten', brName: 'Sint Maarten', esName: 'Sint Maarten' },
  { originalName: 'Nepal', brName: 'Nepal', esName: 'Nepal' },
  { originalName: 'Fiji', brName: 'Fiji', esName: 'Fiyi' },
  { originalName: 'Mauritania', brName: 'Mauritânia', esName: 'Mauritania' },
  { originalName: 'Montserrat', brName: 'Montserrat', esName: 'Montserrat' },
  { originalName: 'St. Barth', brName: 'St. Barth', esName: 'St. Barth' },
  { originalName: 'Nicaragua', brName: 'Nicarágua', esName: 'Nicaragua' },
  { originalName: 'Bhutan', brName: 'Butão', esName: 'Bután' },
  { originalName: 'Saint Lucia', brName: 'Santa Lúcia', esName: 'Santa Lucía' },
  { originalName: 'Turks and Caicos', brName: 'Turcos e Caicos', esName: 'Turcas y Caicos' },
  { originalName: 'Gambia', brName: 'Gâmbia', esName: 'Gambia' },
  { originalName: 'CAR', brName: 'República Centro-Africana', esName: 'República Centroafricana' },
  { originalName: 'Chad', brName: 'Chade', esName: 'Chad' },
  { originalName: 'Liberia', brName: 'Libéria', esName: 'Liberia' },
  { originalName: 'Somalia', brName: 'Somália', esName: 'Somalia' },
  { originalName: 'MS Zaandam', brName: 'MS Zaandam', esName: 'MS Zaandam' },
  { originalName: 'Anguilla', brName: 'Anguilla', esName: 'Anguila' },
  { originalName: 'Belize', brName: 'Belize', esName: 'Belice' },
  { originalName: 'British Virgin Islands', brName: 'Ilhas Virgens Britânicas', esName: 'Islas Vírgenes Británicas' },
  { originalName: 'Guinea-Bissau', brName: 'Guiné-Bissau', esName: 'Guinea-Bissau' },
  { originalName: 'Saint Kitts and Nevis', brName: 'São Cristóvão e Nevis', esName: 'San Cristóbal y Nieves' },
  { originalName: 'Papua New Guinea', brName: 'Papua Nova Guiné', esName: 'Papúa Nueva Guinea' },
  { originalName: 'St. Vincent Grenadines', brName: 'São Vicente e Granadinas', esName: 'San Vicente Granadinas' },
  { originalName: 'Timor-Leste', brName: 'Timor-Leste', esName: 'Timor-Leste' }
];
