export const translationEn = {
  locale: 'en',
  Header: {
    subTitle: 'Real Time',
    lastUpdate: 'Last Update',
    utcTime: 'UTC Time',
  },
  Errors: {
    errorTitle: 'Error',
  },
  Configurations: {
    configurations: 'Configurations',
    information:
      'Time lapse between site updates. Turn the switch on and pick a time to refresh the statistics or turn off the switch to freeze updates',
    timeSelect: 'minute',
    timeSelectPl: 'minutes',
    timeSelectHour: 'hour',
  },
  Corona: {
    statisticsTab: 'Statistics',
    newsTab: 'News',
    aboutTab: 'About us',
    tipsTab: 'Tips',
    messageErrorNews: 'An error has occurred in news, please, contact us!',
    messageErrorStatistics: 'An error has occurred in statistics, please, contact us!',
  },
  Global: {
    cardTitle: 'Global Statistics',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered',
  },
  Today: {
    cardTitle: 'Worldwide',
    information: 'Occurrences in the past 24 hours.',
    informationCountry: "Today's country with more deaths.",
    deaths: 'Deaths',
    confirmed: 'Confirmed',
  },
  TableStats: {
    cardTitle: 'Countries Statistics',
    inputSearchCountry: 'Search Country',
    countries: 'Countries',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered',
    critical: 'Critical',
    total: 'Total',
    last24h: 'Last 24h',
    per1m: '1m pop',
    tests: 'Tests',
    percent: 'Percentage',
    paginationPrevious: 'Previous',
    paginationNext: 'Next',
    paginationOf: 'of',
    paginationRows: 'rows',
    paginationPage: 'Page',
    noRowsFound: 'No country found',
  },
  TableInfoModal: {
    title: 'Table Information',
    subTitle: 'Meaning of the columns',
    last24hInfo: ['Last 24h:', 'Occurrences in the last 24 hours'],
    percentInfo: ['Percentage:', 'Based on the total number of confirmed cases'],
    popInfo: ['1m pop:', 'Total number of cases / deaths / tests for every 1 million inhabitants'],
    testsInfo: ['Tests:', 'Total tests performed to detect covid-19'],
    criticalInfo: ['Critical:', 'Total number of people in critical health condition'],
    utcInfo: 'All information is updated according to UTC (Universal Time Coordinated)',
  },
  Graphic: {
    cardTitle: 'Graphics',
    defaultSearchCountry: 'Search country',
    messageErrorParticularCountry: 'An error has occurred in graphic, please, contact us!',
    confirmed: 'Confirmed',
    infecteds: 'Infecteds',
    deaths: 'Deaths',
    recovered: 'Recovered',
    critical: 'Critical',
    europe: 'Europe',
    northAmerica: 'North America',
    southAmerica: 'South America',
    asia: 'Asia',
    africa: 'Africa',
    oceania: 'Oceania',
    peoples: 'Number of people',
    cumulative: 'Cumulative graphic',
    daily: 'Daily graphic',
  },
  News: {
    publishedAt: ['Published at [{{data}}] by {{author}}', 'Published at [{{data}}]'],
  },
  Tips: {
    cardTitle: 'Tips',
    line1:
      "Useful tips to help at decreasing/slowing the corona virus' spread and, also, to help you avoid being contaminated",
    line2: 'Wash your hands with water and soap many times a day. Whenever possible, use hand sanitizer',
    line3: 'Whenever you sneeze or cough, cover your mouth and nose using your arm rather than your hand',
    line4: "Avoid crowds and closed sites, especially if you have the corona virus' symptoms",
    line5: 'Keep the places where you are well ventilated (open the windows whenever possible)',
    line6: 'Do not share personal objects, especially hygiene objects',
    line7: 'Only leave your house when strictly necessary (to go to the grocery store, pharmacy, hospital, etc.)',
    line8: 'Only seek to medical attention if you develop emergency warning signs for covid-19, such as:',
    list1: 'Trouble breathing',
    list2: 'Persistent pain or pressure in the chest',
    list3: 'New confusion or inability to arouse',
    list4: 'Bluish lips or face',
    cardFooter: 'For more information please access: {{informationSite}}',
  },
  About: {
    cardTitle: 'About us',
    line1: 'Thank you for choosing {{site}}',
    line2: 'We appreciate it!',
    line3: 'This site was developed to bring information regarding the corona virus (covid-19) in REAL TIME!',
    line4:
      'The News tab contains important information and links to let you know everything about COVID-19 that is happening around the globe.',
    line5: 'Use the protection tips to find out a better way to protect yourself and your loved ones!',
    line6:
      'This website is the result of my work and my wish to share true/correct information regarding the covid-19 to support our worldwide fight against it.',
    line7: "If you've found this website useful, consider making a donation to support my work!",
    donate: 'Donate',
    dataSource: 'Data Sources',
  },
};

export const translationPtBr = {
  locale: 'pt',
  Header: {
    subTitle: 'Tempo Real',
    lastUpdate: 'Última atualização',
    utcTime: 'Horário UTC',
  },
  Errors: {
    errorTitle: 'Erro',
  },
  Configurations: {
    configurations: 'Configurações',
    information:
      'Intervalo de tempo entre as atualizações do site. Acione o interruptor e escolha um tempo para atualizar as estatísticas ou desligue o interruptor para congelar as atualizações',
    timeSelect: 'minuto',
    timeSelectPl: 'minutos',
    timeSelectHour: 'hora',
  },
  Corona: {
    statisticsTab: 'Estatísticas',
    newsTab: 'Notícias',
    aboutTab: 'Sobre nós',
    tipsTab: 'Dicas',
    messageErrorNews: 'Ocorreu um erro ao carregar as notícias. Por favor, entre em contato conosco!',
    messageErrorStatistics: 'Ocorreu um erro ao carregar as estatísticas. Por favor, entre em contato conosco!',
    errorTitle: 'Erro',
  },
  Global: {
    cardTitle: 'Estatísticas Globais',
    confirmed: 'Confirmados',
    infecteds: 'Infectados',
    deaths: 'Mortes',
    recovered: 'Recuperados',
  },
  Today: {
    cardTitle: 'No mundo todo',
    information: 'Ocorrências nas últimas 24 horas.',
    informationCountry: 'País com mais mortes hoje.',
    deaths: 'Mortes',
    confirmed: 'Confirmados',
  },
  TableStats: {
    cardTitle: 'Estatísticas por País',
    inputSearchCountry: 'Procurar País',
    countries: 'Países',
    confirmed: 'Confirmados',
    infecteds: 'Infectados',
    deaths: 'Mortes',
    recovered: 'Recuperados',
    critical: 'Crítico',
    total: 'Total',
    last24h: 'Últimas 24h',
    per1m: '1m pop',
    tests: 'Testes',
    percent: 'Porcentagem',
    paginationPrevious: 'Anterior',
    paginationNext: 'Próxima',
    paginationOf: 'de',
    paginationRows: 'linhas',
    paginationPage: 'Página',
    noRowsFound: 'Nenhum país encontrado',
  },
  TableInfoModal: {
    title: 'Informações sobre a Tabela',
    subTitle: 'Significado das colunas',
    last24hInfo: ['Últimas 24h:', 'Ocorrências nas últimas 24 horas'],
    percentInfo: ['Porcentagem:', 'Cálculo da porcentagem baseada no total de casos confirmados'],
    popInfo: ['1m pop:', 'Total de casos / mortes / testes para cada 1 milhão de habitantes'],
    testsInfo: ['Testes:', 'Total de testes realizados para detectar covid-19'],
    criticalInfo: ['Crítico:', 'Total de pessoas em estado crítico de saúde'],
    utcInfo: 'Todas as informações são baseadas e atualizadas de acordo com o horário UTC (Universal Time Coordinated)',
  },
  Graphic: {
    cardTitle: 'Gráficos',
    defaultSearchCountry: 'Procure um país',
    messageErrorParticularCountry: 'Ocorreu um erro ao carregar o gráfico. Por favor, entre em contato conosco!',
    confirmed: 'Confirmados',
    infecteds: 'Infectados',
    deaths: 'Mortes',
    recovered: 'Recuperados',
    critical: 'Crítico',
    europe: 'Europa',
    northAmerica: 'América do Norte',
    southAmerica: 'América do Sul',
    asia: 'Ásia',
    africa: 'África',
    oceania: 'Oceânia',
    peoples: 'Número de pessoas',
    cumulative: 'Gráfico cumulativo',
    daily: 'Gráfico diário',
  },
  News: {
    publishedAt: ['Publicado em [{{data}}] por {{author}}', 'Publicado em [{{data}}]'],
  },
  Tips: {
    cardTitle: 'Dicas',
    line1: 'Sugestões para reduzir a disseminação do corona vírus e evitar ser contaminado.',
    line2: 'Lave as mãos com água e sabão frequentemente. Quando isso não for possível, use álcool em gel',
    line3: 'Ao espirrar ou tossir cubra o nariz e boca, de preferência com o braço',
    line4: 'Evite aglomerações e lugares fechados, principalmente se estiver com sintomas',
    line5: 'Mantenha os ambientes bem arejados',
    line6: 'Não compartilhe objetos pessoais',
    line7: 'Só saia de casa se for realmente necessário',
    line8: 'Procure por assistência médica somente se desenvolver os sinais de emergência da covid-19 abaixo:',
    list1: 'Dificuldade para respirar',
    list2: 'Dor ou pressão persistente no peito',
    list3: 'Confusão mental e falta de atenção',
    list4: 'Rosto ou lábios pálidos',
    cardFooter: 'Para mais informações acesse o site: {{informationSite}}',
  },
  About: {
    cardTitle: 'Sobre nós',
    line1: 'Obrigado por escolher o {{site}}',
    line2: 'Nós agradecemos!',
    line3: 'Esse site foi desenvolvido para trazer informações sobre o coronavírus (covid-19) em TEMPO REAL!',
    line4:
      'A guia Notícias contém informações e links importantes para que você saiba tudo sobre o COVID-19 ao redor de todo o mundo.',
    line5: 'Use as dicas de proteção para descobrir uma maneira melhor de proteger você e seus entes queridos!',
    line6:
      'Esse site é resultado do meu trabalho e meu desejo de compartilhar informações verdadeiras/corretas sobre o covid-19 para apoiar nossa luta mundial contra ele.',
    line7: 'Se você achou esse site útil, considere fazer uma doação para apoiar meu trabalho!',
    donate: 'Doar',
    dataSource: 'Fontes de dados',
  },
};

export const translationEs = {
  locale: 'es',
  Header: {
    subTitle: 'Tiempo real',
    lastUpdate: 'Última actualización',
    utcTime: 'Hora UTC',
  },
  Errors: {
    errorTitle: 'Error',
  },
  Configurations: {
    configurations: 'Configuraciones',
    information:
      'Lapso de tiempo entre actualizaciones del sitio. Encienda el interruptor y elija un tiempo para actualizar las estadísticas o apague el interruptor para congelar las actualizaciones',
    timeSelect: 'minuto',
    timeSelectPl: 'minutos',
    timeSelectHour: 'hora',
  },
  Corona: {
    statisticsTab: 'Estadísticas',
    newsTab: 'Noticias',
    aboutTab: 'Sobre',
    tipsTab: 'Consejos',
    messageErrorNews: 'Se ha producido un error en las noticias, contáctanos.',
    messageErrorStatistics: 'Se ha producido un error en las estadísticas, contáctenos.',
  },
  Global: {
    cardTitle: 'Estadísticas Globales',
    confirmed: 'Confirmados',
    infecteds: 'Infectados',
    deaths: 'Muertes',
    recovered: 'Recuperados',
  },
  Today: {
    cardTitle: 'En todo el mundo',
    information: 'Ocurrencias en las últimas 24 horas.',
    informationCountry: 'El país de hoy con más muertes.',
    deaths: 'Muertes',
    confirmed: 'Confirmados',
  },
  TableStats: {
    cardTitle: 'Estadísticas de Países',
    inputSearchCountry: 'Buscar país',
    countries: 'Países',
    confirmed: 'Confirmados',
    infecteds: 'Infectados',
    deaths: 'Muertes',
    recovered: 'Recuperados',
    critical: 'Critico',
    total: 'Total',
    last24h: 'Últimas 24h',
    per1m: '1m pop',
    tests: 'Pruebas',
    percent: 'Porcentaje',
    paginationPrevious: 'Anterior',
    paginationNext: 'Siguiente',
    paginationOf: 'de',
    paginationRows: 'filas',
    paginationPage: 'Pagina',
    noRowsFound: 'Ningún país encontrado',
  },
  TableInfoModal: {
    title: 'Información de tabla',
    subTitle: 'Significado de las columnas',
    last24hInfo: ['Últimas 24h:', 'Ocurrencias en las últimas 24 horas'],
    percentInfo: ['Porcentaje:', 'Cálculo del porcentaje basado en el número total de casos confirmados'],
    popInfo: ['1m pop:', 'Total de casos / muertes / pruebas por cada 1 millón de habitantes'],
    testsInfo: ['Pruebas:', 'Pruebas totales realizadas para detectar covid-19'],
    criticalInfo: ['Critico:', 'Número total de personas en estado crítico de salud'],
    utcInfo: 'Toda la información se basa y actualiza de acuerdo con UTC (Universal Time Coordinated)',
  },
  Graphic: {
    cardTitle: 'Gráficos',
    defaultSearchCountry: 'Buscar un pais',
    messageErrorParticularCountry: 'Se ha producido un error (Gráfico), contáctanos',
    confirmed: 'Confirmados',
    infecteds: 'Infectados',
    deaths: 'Muertes',
    recovered: 'Recuperados',
    critical: 'Critico',
    europe: 'Europa',
    northAmerica: 'Norteamérica',
    southAmerica: 'Sudamerica',
    asia: 'Asia',
    africa: 'África',
    oceania: 'Oceanía',
    peoples: 'Cantidad de personas',
    cumulative: 'Gráfico acumulativo',
    daily: 'Gráfico diario',
  },
  News: {
    publishedAt: ['Publicado en [{{data}}] por {{author}}', 'publicado en [{{data}}]'],
  },
  Tips: {
    cardTitle: 'Consejos',
    line1: 'Sugerencias para reducir la propagación del virus corona y evitar contaminarse',
    line2: 'Lávese las manos con agua y jabón con frecuencia. Cuando no es posible usar alcohol gel',
    line3: 'Al estornudar o toser, cubra su nariz y boca preferiblemente con su brazo',
    line4: 'Evite las multitudes y los lugares cerrados, especialmente si tiene síntomas',
    line5: 'Mantenga los ambientes bien ventilados',
    line6: 'No comparta artículos personales',
    line7: 'Solo sal de la casa si es realmente necesario',
    line8: 'Busque el centro de salud más cercano en caso de empeoramiento de los síntomas:',
    list1: 'Dificultad para respirar',
    list2: 'Dolor o presión persistente en el pecho',
    list3: 'Confusión mental y falta de atención',
    list4: 'Cara o labios pálidos',
    cardFooter: 'Para obtener más información, acceda a: {{informationSite}}',
  },
  About: {
    cardTitle: 'Sobre nosotros',
    line1: 'Gracias por elegir {{site}}',
    line2: '¡Lo apreciamos!',
    line3: 'Este sitio fue desarrollado para brindar información sobre el virus corona (covid-19) in ¡TIEMPO REAL!',
    line4:
      'La pestaña Noticias contiene información importante y enlaces para hacerle saber todo acerca de COVID-19 que está sucediendo en todo el mundo.',
    line5:
      '¡Use los consejos de protección para descubrir una mejor manera de protegerse y proteger a su ser querido unos!',
    line6:
      'Este sitio web es el resultado de mi trabajo y mi deseo de compartir verdadero / correcto información con respecto al covid-19 para apoyar nuestra lucha mundial contra él.',
    line7: 'Si este sitio le resulta útil, considere hacer una donación para apoyar mi trabajo',
    donate: 'Donar',
    dataSource: 'Fuentes de datos',
  },
};

export const countriesTranslated = [
  { originalName: 'Afghanistan', brName: 'Afeganistão', esName: 'Afganistán', tlc: 'AFG', continent: 'Asia' },
  { originalName: 'Albania', brName: 'Albânia', esName: 'Albania', tlc: 'ALB', continent: 'Europe' },
  { originalName: 'Algeria', brName: 'Argélia', esName: 'Argelia', tlc: 'DZA', continent: 'Africa' },
  { originalName: 'Andorra', brName: 'Andorra', esName: 'Andorra', tlc: 'AND', continent: 'Europe' },
  { originalName: 'Angola', brName: 'Angola', esName: 'Angola', tlc: 'AGO', continent: 'Africa' },
  { originalName: 'Anguilla', brName: 'Anguilla', esName: 'Anguila', tlc: 'AIA', continent: 'North America' },
  {
    originalName: 'Antigua and Barbuda',
    brName: 'Antígua e Barbuda',
    esName: 'Antigua y Barbuda',
    tlc: 'ATG',
    continent: 'North America',
  },
  { originalName: 'Argentina', brName: 'Argentina', esName: 'Argentina', tlc: 'ARG', continent: 'South America' },
  { originalName: 'Armenia', brName: 'Armênia', esName: 'Armenia', tlc: 'ARM', continent: 'Asia' },
  { originalName: 'Aruba', brName: 'Aruba', esName: 'Aruba', tlc: 'ABW', continent: 'South America' },
  { originalName: 'Australia', brName: 'Austrália', esName: 'Australia', tlc: 'AUS', continent: 'Oceania' },
  { originalName: 'Austria', brName: 'Austria', esName: 'Austria', tlc: 'AUT', continent: 'Europe' },
  { originalName: 'Azerbaijan', brName: 'Azerbaijão', esName: 'Azerbaiyán', tlc: 'AZE', continent: 'Europe' },
  { originalName: 'Bahamas', brName: 'Bahamas', esName: 'Bahamas', tlc: 'BHS', continent: 'North America' },
  { originalName: 'Bahrain', brName: 'Barém', esName: 'Bahrein', tlc: 'BHR', continent: 'Asia' },
  { originalName: 'Bangladesh', brName: 'Bangladesh', esName: 'Bangladesh', tlc: 'BGD', continent: 'Asia' },
  { originalName: 'Barbados', brName: 'Barbados', esName: 'Barbados', tlc: 'BRB', continent: 'North America' },
  { originalName: 'Belarus', brName: 'Bielorrússia', esName: 'Bielorrusia', tlc: 'BLR', continent: 'Europe' },
  { originalName: 'Belgium', brName: 'Bélgica', esName: 'Bélgica', tlc: 'BEL', continent: 'Europe' },
  { originalName: 'Belize', brName: 'Belize', esName: 'Belice', tlc: 'BLZ', continent: 'North America' },
  { originalName: 'Benin', brName: 'Benin', esName: 'Benin', tlc: 'BEN', continent: 'Africa' },
  { originalName: 'Bermuda', brName: 'Bermudas', esName: 'Islas Bermudas', tlc: 'BMU', continent: 'North America' },
  { originalName: 'Bhutan', brName: 'Butão', esName: 'Bután', tlc: 'BTN', continent: 'Asia' },
  { originalName: 'Bolivia', brName: 'Bolívia', esName: 'Bolivia', tlc: 'BOL', continent: 'South America' },
  {
    originalName: 'Bosnia and Herzegovina',
    brName: 'Bósnia e Herzegovina',
    esName: 'Bosnia y Herzegovina',
    tlc: 'BIH',
    continent: 'Europe',
  },
  { originalName: 'Brazil', brName: 'Brasil', esName: 'Brasil', tlc: 'BRA', continent: 'South America' },
  {
    originalName: 'British Virgin Islands',
    brName: 'Ilhas Virgens Britânicas',
    esName: 'Islas Vírgenes Británicas',
    tlc: 'VGB',
    continent: 'North America',
  },
  { originalName: 'Brunei', brName: 'Brunei', esName: 'Brunei', tlc: 'BRN', continent: 'Asia' },
  { originalName: 'Bulgaria', brName: 'Bulgária', esName: 'Bulgaria', tlc: 'BGR', continent: 'Europe' },
  { originalName: 'Burkina Faso', brName: 'Burkina Faso', esName: 'Burkina Faso', tlc: 'BFA', continent: 'Africa' },
  { originalName: 'Cabo Verde', brName: 'Cabo Verde', esName: 'Cabo Verde', tlc: 'CPV', continent: 'Africa' },
  { originalName: 'Cambodia', brName: 'Camboja', esName: 'Camboya', tlc: 'KHM', continent: 'Asia' },
  { originalName: 'Cameroon', brName: 'Camarões', esName: 'Camerún', tlc: 'CMR', continent: 'Africa' },
  { originalName: 'Canada', brName: 'Canadá', esName: 'Canadá', tlc: 'CAN', continent: 'North America' },
  {
    originalName: 'CAR',
    brName: 'República Centro-Africana',
    esName: 'República Centroafricana',
    tlc: 'CAF',
    continent: 'Africa',
  },
  {
    originalName: 'Cayman Islands',
    brName: 'Ilhas Cayman',
    esName: 'Islas Caimán',
    tlc: 'CYM',
    continent: 'North America',
  },
  { originalName: 'Chad', brName: 'Chade', esName: 'Chad', tlc: 'TCD', continent: 'Africa' },
  {
    originalName: 'Channel Islands',
    brName: 'Ilhas do Canal',
    esName: 'Islas del Canal',
    tlc: 'CNI',
    continent: 'Europe',
  },
  { originalName: 'Chile', brName: 'Chile', esName: 'Chile', tlc: 'CHL', continent: 'South America' },
  { originalName: 'China', brName: 'China', esName: 'China', tlc: 'CHN', continent: 'Asia' },
  { originalName: 'Colombia', brName: 'Colômbia', esName: 'Colombia', tlc: 'COL', continent: 'South America' },
  { originalName: 'Congo', brName: 'Congo', esName: 'Congo', tlc: 'COG', continent: 'Africa' },
  { originalName: 'Costa Rica', brName: 'Costa Rica', esName: 'Costa Rica', tlc: 'CRI', continent: 'North America' },
  { originalName: 'Croatia', brName: 'Croácia', esName: 'Croacia', tlc: 'HRV', continent: 'Europe' },
  { originalName: 'Cuba', brName: 'Cuba', esName: 'Cuba', tlc: 'CUB', continent: 'North America' },
  { originalName: 'Curaçao', brName: 'Curaçao', esName: 'Curazao', tlc: 'CUW', continent: 'South America' },
  { originalName: 'Cyprus', brName: 'Chipre', esName: 'Chipre', tlc: 'CYP', continent: 'Europe' },
  { originalName: 'Czechia', brName: 'Czechia', esName: 'Chequia', tlc: 'CZE', continent: 'Europe' },
  { originalName: 'Denmark', brName: 'Dinamarca', esName: 'Dinamarca', tlc: 'DNK', continent: 'Europe' },
  {
    originalName: 'Diamond Princess',
    brName: 'Diamond Princess',
    esName: 'Diamond Princess',
    tlc: '',
    continent: 'NA',
  },
  { originalName: 'Djibouti', brName: 'Djibuti', esName: 'Djibouti', tlc: 'DJI', continent: 'Africa' },
  { originalName: 'Dominica', brName: 'Dominica', esName: 'Dominica', tlc: 'DMA', continent: 'North America' },
  {
    originalName: 'Dominican Republic',
    brName: 'República Dominicana',
    esName: 'República Dominicana',
    tlc: 'DOM',
    continent: 'North America',
  },
  {
    originalName: 'DRC',
    brName: 'República Democrática do Congo',
    esName: 'República Democrática del Congo',
    tlc: 'COD',
    continent: 'Africa',
  },
  { originalName: 'Ecuador', brName: 'Equador', esName: 'Ecuador', tlc: 'ECU', continent: 'South America' },
  { originalName: 'Egypt', brName: 'Egito', esName: 'Egipto', tlc: 'EGY', continent: 'Africa' },
  { originalName: 'El Salvador', brName: 'El Salvador', esName: 'El Salvador', tlc: 'SLV', continent: 'North America' },
  {
    originalName: 'Equatorial Guinea',
    brName: 'Guiné Equatorial',
    esName: 'Guinea Ecuatorial',
    tlc: 'GNQ',
    continent: 'Africa',
  },
  { originalName: 'Eritrea', brName: 'Eritreia', esName: 'Eritrea', tlc: 'ERI', continent: 'Africa' },
  { originalName: 'Estonia', brName: 'Estônia', esName: 'Estonia', tlc: 'EST', continent: 'Europe' },
  { originalName: 'Eswatini', brName: 'Eswatini', esName: 'Eswatini', tlc: 'SWZ', continent: 'Africa' },
  { originalName: 'Ethiopia', brName: 'Etiópia', esName: 'Etiopía', tlc: 'ETH', continent: 'Africa' },
  { originalName: 'Faeroe Islands', brName: 'Ilhas Faroé', esName: 'Islas Feroe', tlc: 'FRO', continent: 'Europe' },
  { originalName: 'Fiji', brName: 'Fiji', esName: 'Fiyi', tlc: 'FJI', continent: 'Oceania' },
  { originalName: 'Finland', brName: 'Finlândia', esName: 'Finlandia', tlc: 'FIN', continent: 'Europe' },
  { originalName: 'France', brName: 'França', esName: 'Francia', tlc: 'FRA', continent: 'Europe' },
  {
    originalName: 'French Guiana',
    brName: 'Guiana Francesa',
    esName: 'Guayana Francesa',
    tlc: 'GUF',
    continent: 'South America',
  },
  {
    originalName: 'French Polynesia',
    brName: 'Polinésia Francesa',
    esName: 'Polinesia francés',
    tlc: 'PYF',
    continent: 'Oceania',
  },
  { originalName: 'Gabon', brName: 'Gabão', esName: 'Gabón', tlc: 'GAB', continent: 'Africa' },
  { originalName: 'Gambia', brName: 'Gâmbia', esName: 'Gambia', tlc: 'GMB', continent: 'Africa' },
  { originalName: 'Georgia', brName: 'Geórgia', esName: 'Georgia', tlc: 'GEO', continent: 'Europe' },
  { originalName: 'Germany', brName: 'Alemanha', esName: 'Alemania', tlc: 'DEU', continent: 'Europe' },
  { originalName: 'Ghana', brName: 'Gana', esName: 'Ghana', tlc: 'GHA', continent: 'Africa' },
  { originalName: 'Gibraltar', brName: 'Gibraltar', esName: 'Gibraltar', tlc: 'GIB', continent: 'Europe' },
  { originalName: 'Greece', brName: 'Grécia', esName: 'Grecia', tlc: 'GRC', continent: 'Europe' },
  { originalName: 'Greenland', brName: 'Gronelândia', esName: 'Groenlandia', tlc: 'GRL', continent: 'North America' },
  { originalName: 'Grenada', brName: 'Granada', esName: 'Granada', tlc: 'GRD', continent: 'North America' },
  { originalName: 'Guadeloupe', brName: 'Guadalupe', esName: 'Guadalupe', tlc: 'GLP', continent: 'North America' },
  { originalName: 'Guatemala', brName: 'Guatemala', esName: 'Guatemala', tlc: 'GTM', continent: 'North America' },
  { originalName: 'Guinea', brName: 'Guiné', esName: 'Guinea', tlc: 'GIN', continent: 'Africa' },
  { originalName: 'Guinea-Bissau', brName: 'Guiné-Bissau', esName: 'Guinea-Bissau', tlc: 'GNB', continent: 'Africa' },
  { originalName: 'Guyana', brName: 'Guiana', esName: 'Guayana', tlc: 'GUY', continent: 'South America' },
  { originalName: 'Haiti', brName: 'Haiti', esName: 'Haití', tlc: 'HTI', continent: 'North America' },
  { originalName: 'Honduras', brName: 'Honduras', esName: 'Honduras', tlc: 'HND', continent: 'North America' },
  { originalName: 'Hong Kong', brName: 'Hong Kong', esName: 'Hong Kong', tlc: 'HKG', continent: 'Asia' },
  { originalName: 'Hungary', brName: 'Hungria', esName: 'Hungría', tlc: 'HUN', continent: 'Europe' },
  { originalName: 'Iceland', brName: 'Islândia', esName: 'Islandia', tlc: 'ISL', continent: 'Europe' },
  { originalName: 'India', brName: 'India', esName: 'India', tlc: 'IND', continent: 'Asia' },
  { originalName: 'Indonesia', brName: 'Indonésia', esName: 'Indonesia', tlc: 'IDN', continent: 'Asia' },
  { originalName: 'Iran', brName: 'Irã', esName: 'Iran', tlc: 'IRN', continent: 'Asia' },
  { originalName: 'Iraq', brName: 'Iraque', esName: 'Irak', tlc: 'IRQ', continent: 'Asia' },
  { originalName: 'Ireland', brName: 'Irlanda', esName: 'Irlanda', tlc: 'IRL', continent: 'Europe' },
  { originalName: 'Isle of Man', brName: 'Ilha de Man', esName: 'Isla del hombre', tlc: 'IMN', continent: 'Europe' },
  { originalName: 'Israel', brName: 'Israel', esName: 'Israel', tlc: 'ISR', continent: 'Asia' },
  { originalName: 'Italy', brName: 'Itália', esName: 'Italia', tlc: 'ITA', continent: 'Europe' },
  {
    originalName: 'Ivory Coast',
    brName: 'Costa do Marfim',
    esName: 'Costa de Marfil',
    tlc: 'CIV',
    continent: 'Africa',
  },
  { originalName: 'Jamaica', brName: 'Jamaica', esName: 'Jamaica', tlc: 'JAM', continent: 'North America' },
  { originalName: 'Japan', brName: 'Japão', esName: 'Japón', tlc: 'JPN', continent: 'Asia' },
  { originalName: 'Jordan', brName: 'Jordânia', esName: 'Jordán', tlc: 'JOR', continent: 'Asia' },
  { originalName: 'Kazakhstan', brName: 'Cazaquistão', esName: 'Kazajstán', tlc: 'KAZ', continent: 'Europe' },
  { originalName: 'Kenya', brName: 'Quênia', esName: 'Kenia', tlc: 'KEN', continent: 'Africa' },
  { originalName: 'Kuwait', brName: 'Kuwait', esName: 'Kuwait', tlc: 'KWT', continent: 'Asia' },
  { originalName: 'Kyrgyzstan', brName: 'Quirguistão', esName: 'Kirguistán', tlc: 'KGZ', continent: 'Asia' },
  { originalName: 'Laos', brName: 'Laos', esName: 'Laos', tlc: 'LAO', continent: 'Asia' },
  { originalName: 'Latvia', brName: 'Letônia', esName: 'Letonia', tlc: 'LVA', continent: 'Europe' },
  { originalName: 'Lebanon', brName: 'Líbano', esName: 'Líbano', tlc: 'LBN', continent: 'Asia' },
  { originalName: 'Liberia', brName: 'Libéria', esName: 'Liberia', tlc: 'LBR', continent: 'Africa' },
  { originalName: 'Libya', brName: 'Líbia', esName: 'Libia', tlc: 'LBY', continent: 'Africa' },
  { originalName: 'Liechtenstein', brName: 'Liechtenstein', esName: 'Liechtenstein', tlc: 'LIE', continent: 'Europe' },
  { originalName: 'Lithuania', brName: 'Lituânia', esName: 'Lituania', tlc: 'LTU', continent: 'Europe' },
  { originalName: 'Luxembourg', brName: 'Luxemburgo', esName: 'Luxemburgo', tlc: 'LUX', continent: 'Europe' },
  { originalName: 'Macao', brName: 'Macau', esName: 'Macao', tlc: 'MAC', continent: 'Asia' },
  { originalName: 'Madagascar', brName: 'Madagáscar', esName: 'Madagascar', tlc: 'MDG', continent: 'Africa' },
  { originalName: 'Malaysia', brName: 'Malásia', esName: 'Malasia', tlc: 'MYS', continent: 'Asia' },
  { originalName: 'Maldives', brName: 'Maldivas', esName: 'Maldivas', tlc: 'MDV', continent: 'Asia' },
  { originalName: 'Mali', brName: 'Mali', esName: 'Mali', tlc: 'MLI', continent: 'Africa' },
  { originalName: 'Malta', brName: 'Malta', esName: 'Malta', tlc: 'MLT', continent: 'Europe' },
  { originalName: 'Martinique', brName: 'Martinica', esName: 'Martinica', tlc: 'MTQ', continent: 'North America' },
  { originalName: 'Mauritania', brName: 'Mauritânia', esName: 'Mauritania', tlc: 'MRT', continent: 'Africa' },
  { originalName: 'Mauritius', brName: 'Maurícia', esName: 'Mauricio', tlc: 'MUS', continent: 'Africa' },
  { originalName: 'Mayotte', brName: 'Mayotte', esName: 'Mayotte', tlc: 'MYT', continent: 'Africa' },
  { originalName: 'Mexico', brName: 'México', esName: 'Mexico', tlc: 'MEX', continent: 'North America' },
  { originalName: 'Moldova', brName: 'Moldova', esName: 'Moldavia', tlc: 'MDA', continent: 'Europe' },
  { originalName: 'Monaco', brName: 'Mônaco', esName: 'Mónaco', tlc: 'MCO', continent: 'Europe' },
  { originalName: 'Mongolia', brName: 'Mongólia', esName: 'Mongolia', tlc: 'MNG', continent: 'Asia' },
  { originalName: 'Montenegro', brName: 'Montenegro', esName: 'Montenegro', tlc: 'MNE', continent: 'Europe' },
  { originalName: 'Montserrat', brName: 'Montserrat', esName: 'Montserrat', tlc: 'MSR', continent: 'North America' },
  { originalName: 'Morocco', brName: 'Marrocos', esName: 'Marruecos', tlc: 'MAR', continent: 'Africa' },
  { originalName: 'Mozambique', brName: 'Moçambique', esName: 'Mozambique', tlc: 'MOZ', continent: 'Africa' },
  { originalName: 'MS Zaandam', brName: 'MS Zaandam', esName: 'MS Zaandam', tlc: '', continent: 'NA' },
  { originalName: 'Myanmar', brName: 'Myanmar', esName: 'Myanmar', tlc: 'MMR', continent: 'Asia' },
  { originalName: 'Namibia', brName: 'Namíbia', esName: 'Namibia', tlc: 'NAM', continent: 'Africa' },
  { originalName: 'Nepal', brName: 'Nepal', esName: 'Nepal', tlc: 'NPL', continent: 'Asia' },
  { originalName: 'Netherlands', brName: 'Países Baixos', esName: 'Países Bajos', tlc: 'NLD', continent: 'Europe' },
  {
    originalName: 'New Caledonia',
    brName: 'Nova Caledônia',
    esName: 'Nueva Caledonia',
    tlc: 'NCL',
    continent: 'Oceania',
  },
  { originalName: 'New Zealand', brName: 'Nova Zelândia', esName: 'Nueva Zelanda', tlc: 'NZL', continent: 'Oceania' },
  { originalName: 'Nicaragua', brName: 'Nicarágua', esName: 'Nicaragua', tlc: 'NIC', continent: 'North America' },
  { originalName: 'Niger', brName: 'Níger', esName: 'Níger', tlc: 'NER', continent: 'Africa' },
  { originalName: 'Nigeria', brName: 'Nigéria', esName: 'Nigeria', tlc: 'NGA', continent: 'Africa' },
  {
    originalName: 'North Macedonia',
    brName: 'Macedônia do Norte',
    esName: 'Macedonia del norte',
    tlc: 'MKD',
    continent: 'Europe',
  },
  { originalName: 'Norway', brName: 'Noruega', esName: 'Noruega', tlc: 'NOR', continent: 'Europe' },
  { originalName: 'Oman', brName: 'Omã', esName: 'Omán', tlc: 'OMN', continent: 'Asia' },
  { originalName: 'Pakistan', brName: 'Paquistão', esName: 'Pakistán', tlc: 'PAK', continent: 'Asia' },
  { originalName: 'Palestine', brName: 'Palestina', esName: 'Palestina', tlc: 'PSE', continent: 'Asia' },
  { originalName: 'Panama', brName: 'Panamá', esName: 'Panamá', tlc: 'PAN', continent: 'North America' },
  {
    originalName: 'Papua New Guinea',
    brName: 'Papua Nova Guiné',
    esName: 'Papúa Nueva Guinea',
    tlc: 'PNG',
    continent: 'Oceania',
  },
  { originalName: 'Paraguay', brName: 'Paraguai', esName: 'Paraguay', tlc: 'PRY', continent: 'South America' },
  { originalName: 'Peru', brName: 'Peru', esName: 'Perú', tlc: 'PER', continent: 'South America' },
  { originalName: 'Philippines', brName: 'Filipinas', esName: 'Filipinas', tlc: 'PHL', continent: 'Asia' },
  { originalName: 'Poland', brName: 'Polônia', esName: 'Polonia', tlc: 'POL', continent: 'Europe' },
  { originalName: 'Portugal', brName: 'Portugal', esName: 'Portugal', tlc: 'PRT', continent: 'Europe' },
  { originalName: 'Qatar', brName: 'Catar', esName: 'Katar', tlc: 'QAT', continent: 'Asia' },
  { originalName: 'Romania', brName: 'Romênia', esName: 'Rumania', tlc: 'ROU', continent: 'Europe' },
  { originalName: 'Russia', brName: 'Rússia', esName: 'Rusia', tlc: 'RUS', continent: 'Asia' },
  { originalName: 'Rwanda', brName: 'Ruanda', esName: 'Ruanda', tlc: 'RWA', continent: 'Africa' },
  { originalName: 'Réunion', brName: 'Reunião', esName: 'Reunión', tlc: 'REU', continent: 'Africa' },
  { originalName: 'S. Korea', brName: 'Coreia do Sul', esName: 'Corea del Sur', tlc: 'KOR', continent: 'Asia' },
  {
    originalName: 'Saint Kitts and Nevis',
    brName: 'São Cristóvão e Nevis',
    esName: 'San Cristóbal y Nieves',
    tlc: 'KNA',
    continent: 'North America',
  },
  { originalName: 'Saint Lucia', brName: 'Santa Lúcia', esName: 'Santa Lucía', tlc: 'LCA', continent: 'North America' },
  {
    originalName: 'Saint Martin',
    brName: 'São Martinho',
    esName: 'San Martín',
    tlc: 'MAF',
    continent: 'North America',
  },
  { originalName: 'San Marino', brName: 'San Marino', esName: 'San Marino', tlc: 'SMR', continent: 'Europe' },
  { originalName: 'Saudi Arabia', brName: 'Arábia Saudita', esName: 'Arabia Saudita', tlc: 'SAU', continent: 'Asia' },
  { originalName: 'Senegal', brName: 'Senegal', esName: 'Senegal', tlc: 'SEN', continent: 'Africa' },
  { originalName: 'Serbia', brName: 'Sérvia', esName: 'Serbia', tlc: 'SRB', continent: 'Europe' },
  { originalName: 'Seychelles', brName: 'Seychelles', esName: 'Seychelles', tlc: 'SYC', continent: 'Africa' },
  { originalName: 'Singapore', brName: 'Cingapura', esName: 'Singapur', tlc: 'SGP', continent: 'Asia' },
  {
    originalName: 'Sint Maarten',
    brName: 'Sint Maarten',
    esName: 'Sint Maarten',
    tlc: 'SXM',
    continent: 'North America',
  },
  { originalName: 'Slovakia', brName: 'Eslováquia', esName: 'Eslovaquia', tlc: 'SVK', continent: 'Europe' },
  { originalName: 'Slovenia', brName: 'Eslovênia', esName: 'Eslovenia', tlc: 'SVN', continent: 'Europe' },
  { originalName: 'Somalia', brName: 'Somália', esName: 'Somalia', tlc: 'SOM', continent: 'Africa' },
  { originalName: 'South Africa', brName: 'Africa do Sul', esName: 'Sudáfrica', tlc: 'ZAF', continent: 'Africa' },
  { originalName: 'Spain', brName: 'Espanha', esName: 'España', tlc: 'ESP', continent: 'Europe' },
  { originalName: 'Sri Lanka', brName: 'Sri Lanka', esName: 'Sri Lanka', tlc: 'LKA', continent: 'Asia' },
  { originalName: 'St. Barth', brName: 'St. Barth', esName: 'St. Barth', tlc: 'SBH', continent: 'North America' },
  {
    originalName: 'St. Vincent Grenadines',
    brName: 'São Vicente e Granadinas',
    esName: 'San Vicente Granadinas',
    tlc: 'VCT',
    continent: 'North America',
  },
  { originalName: 'Sudan', brName: 'Sudão', esName: 'Sudán', tlc: 'SDN', continent: 'Africa' },
  { originalName: 'Suriname', brName: 'Suriname', esName: 'Surinam', tlc: 'SUR', continent: 'South America' },
  { originalName: 'Sweden', brName: 'Suécia', esName: 'Suecia', tlc: 'SWE', continent: 'Europe' },
  { originalName: 'Switzerland', brName: 'Suíça', esName: 'Suiza', tlc: 'CHE', continent: 'Europe' },
  { originalName: 'Syria', brName: 'Síria', esName: 'Siria', tlc: 'SYR', continent: 'Asia' },
  { originalName: 'Taiwan', brName: 'Taiwan', esName: 'Taiwán', tlc: 'TWN', continent: 'Asia' },
  { originalName: 'Tanzania', brName: 'Tanzânia', esName: 'Tanzania', tlc: 'TZA', continent: 'Africa' },
  { originalName: 'Thailand', brName: 'Tailândia', esName: 'Tailandia', tlc: 'THA', continent: 'Asia' },
  { originalName: 'Timor-Leste', brName: 'Timor-Leste', esName: 'Timor-Leste', tlc: 'TLS', continent: 'Asia' },
  { originalName: 'Togo', brName: 'Togo', esName: 'Togo', tlc: 'TGO', continent: 'Africa' },
  {
    originalName: 'Trinidad and Tobago',
    brName: 'Trindade e Tobago',
    esName: 'Trinidad y Tobago',
    tlc: 'TTO',
    continent: 'North America',
  },
  { originalName: 'Tunisia', brName: 'Tunísia', esName: 'Túnez', tlc: 'TUN', continent: 'Africa' },
  { originalName: 'Turkey', brName: 'Turquia', esName: 'Turquía', tlc: 'TUR', continent: 'Europe' },
  {
    originalName: 'Turks and Caicos',
    brName: 'Turcos e Caicos',
    esName: 'Turcas y Caicos',
    tlc: 'TCA',
    continent: 'North America',
  },
  {
    originalName: 'UAE',
    brName: 'Emirados Árabes Unidos',
    esName: 'Emiratos Árabes Unidos',
    tlc: 'ARE',
    continent: 'Asia',
  },
  { originalName: 'Uganda', brName: 'Uganda', esName: 'Uganda', tlc: 'UGA', continent: 'Africa' },
  { originalName: 'UK', brName: 'Reino Unido', esName: 'Reino Unido', tlc: 'GBR', continent: 'Europe' },
  { originalName: 'Ukraine', brName: 'Ucrânia', esName: 'Ucrania', tlc: 'UKR', continent: 'Europe' },
  { originalName: 'Uruguay', brName: 'Uruguai', esName: 'Uruguay', tlc: 'URY', continent: 'South America' },
  { originalName: 'USA', brName: 'Estados Unidos', esName: 'Estados Unidos', tlc: 'USA', continent: 'North America' },
  { originalName: 'Uzbekistan', brName: 'Usbequistão', esName: 'Uzbekistán', tlc: 'UZB', continent: 'Asia' },
  {
    originalName: 'Vatican City',
    brName: 'Cidade do Vaticano',
    esName: 'Ciudad del Vaticano',
    tlc: 'VAT',
    continent: 'Europe',
  },
  { originalName: 'Venezuela', brName: 'Venezuela', esName: 'Venezuela', tlc: 'VEN', continent: 'South America' },
  { originalName: 'Vietnam', brName: 'Vietnã', esName: 'Vietnam', tlc: 'VNM', continent: 'Asia' },
  { originalName: 'Zambia', brName: 'Zâmbia', esName: 'Zambia', tlc: 'ZMB', continent: 'Africa' },
  { originalName: 'Zimbabwe', brName: 'Zimbábue', esName: 'Zimbabue', tlc: 'ZWE', continent: 'Africa' },
];
